### ISSUE TITLE
[BUG] [MOBILE] No margin between social media icons and FA logo on footer of every page

### ISSUE THREAD

**Issue by guywhodiesfirst** [fictadvisor/fictadvisor-web#744] opened 2023-09-26 17:02 UTC
Bug type: UI/UX
Priority: mid

**Steps to reproduce**
1. Go to any page (i.e. main page)
2. Scroll to the very bottom of the page

**Actual result:** there is no margin between the social media icons and the logo

**Expected result:** there is a 6px margin between the social media icons and the logo

**Environment:**
-deploy: prod
-url: https://fictadvisor.com
-OS: Android
-browser: Opera
![NoMArgins1](https://github.com/fictadvisor/fictadvisor-web/assets/144242408/ac5b579a-cc7c-40ff-a76d-6a385aebee3b)
![NoMargins2](https://github.com/fictadvisor/fictadvisor-web/assets/144242408/03cbbd15-cc27-48b3-ab5c-08129f43c555)

**Comment by Markusplay** [comment] 2023-09-28 11:09
duplicate of #728

**Closed by Markusplay** 2023-09-28 11:09 UTC
Labels: bugfix
